# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e748d812d19dadf54d894f424e7ccf7f63c9b7e64d5be8dddd3c7f2c0edc9401e9205af1e5a010d204cc1fafd28110c9e770982fb3ae275eb671b37e0f70c4

test:
  secret_key_base: 8ff88c16d2b347bb02a41531b5f8f8e2f56920783d409975ed26c23d602a60c3e81dfcd0d3317db4a0bc5f948a7b096fd9abe862f6791441d576418bdc658a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
